auth/urls.py
from django.urls import path

from auth import views

app_name = "auth"

urlpatterns = [
    path("login/", views.AuthView.as_view(), name="login"),
    path("callback/", views.AuthCallbackView.as_view(), name="callback"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
]

conf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("auth.urls")),
    path("queues/<uuid:queue_pk>/cases/<uuid:pk>/", include("cases.urls")),
    path("flags/", include("flags.urls")),
    path("document-templates/", include("letter_templates.urls")),
    path("organisations/", include("organisations.urls")),
    path("queues/", include("queues.urls")),
    path("team/picklists/", include("picklists.urls")),
    path("team", include("teams.urls")),
    path("users/", include("users.urls")),
]

picklists/urls.py
from django.urls import path

from picklists import views

app_name = "picklists"

urlpatterns = [
    path("", views.Picklists.as_view(), name="picklists"),
    path("<uuid:pk>/", views.ViewPicklistItem.as_view(), name="picklist_item"),
    path("add/", views.AddPicklistItem.as_view(), name="add"),
    path("<uuid:pk>/edit/", views.EditPicklistItem.as_view(), name="edit"),
    path("<uuid:pk>/edit/deactivate/", views.DeactivatePicklistItem.as_view(), name="deactivate"),
    path("<uuid:pk>/edit/reactivate/", views.ReactivatePicklistItem.as_view(), name="reactivate"),
]

teams/urls.py
from django.urls import path

from teams import views

app_name = "teams"

urlpatterns = [
    path("", views.Team.as_view(), name="team"),
    path("s/", views.TeamsList.as_view(), name="teams"),
    path("s/add/", views.AddTeam.as_view(), name="add"),
    path("s/<uuid:pk>/", views.TeamDetail.as_view(), name="team"),
    path("s/<uuid:pk>/edit/", views.EditTeam.as_view(), name="edit"),
]

users/urls.py
from django.urls import path

from users.views import users, roles

app_name = "users"

urlpatterns = [
    path("", users.UsersList.as_view(), name="users"),
    path("<uuid:pk>/", users.ViewUser.as_view(), name="user"),
    path("add", users.AddUser.as_view(), name="add"),
    path("<uuid:pk>/edit/", users.EditUser.as_view(), name="edit"),
    path("<uuid:pk>/edit/<str:status>/", users.ChangeUserStatus.as_view(), name="change_status"),
    path("profile/", users.ViewProfile.as_view(), name="profile"),
    # Roles
    path("roles/", roles.Roles.as_view(), name="roles"),
    path("roles/add/", roles.AddRole.as_view(), name="add_role"),
    path("roles/<str:pk>/edit/", roles.EditRole.as_view(), name="edit_role"),
]

teams/forms.py
from django.urls import reverse

from lite_content.lite_internal_frontend.teams import AddTeamForm, EditTeamForm
from lite_forms.components import Form, TextInput, BackLink


def add_team_form():
    return Form(
        title=AddTeamForm.TITLE,
        description=AddTeamForm.DESCRIPTION,
        questions=[TextInput(title=AddTeamForm.Name.TITLE, description=AddTeamForm.Name.DESCRIPTION, name="name"),],
        back_link=BackLink(AddTeamForm.BACK_LINK, reverse("teams:teams")),
    )


def edit_team_form():
    return Form(
        title=EditTeamForm.TITLE,
        description=EditTeamForm.DESCRIPTION,
        questions=[TextInput(title=EditTeamForm.Name.TITLE, description=EditTeamForm.Name.DESCRIPTION, name="name"),],
        back_link=BackLink(EditTeamForm.BACK_LINK, reverse("teams:teams")),
    )

picklist_items/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from core.builtins.custom_tags import get_string
from flags.forms import add_flag_form, edit_flag_form
from picklist_items.services import get_picklists, get_picklist_item, put_picklist_item
from libraries.forms.generators import form_page
from users.services import get_gov_user


class PickList(TemplateView):

    def get(self, request, **kwargs):
        data, status_code = get_picklists(request)
        user_data, status_code = get_gov_user(request, str(request.user.lite_api_user_id))

        context = {
            'data': data,
            'title': 'Pick List',
            'user_data': user_data,
        }
        return render(request, 'teams/picklist.html', context)


# class AddFlag(TemplateView):
#     def get(self, request, **kwargs):
#         return form_page(request, add_flag_form())
#
#     def post(self, request, **kwargs):
#         response, status_code = post_flags(request, request.POST)
#         if status_code != 201:
#             return form_page(request, add_flag_form(), data=request.POST, errors=response.get('errors'))
#
#         return redirect(reverse_lazy('flags:flags'))
#
#
# class EditFlag(TemplateView):
#     def get(self, request, **kwargs):
#         data, status_code = get_flag(request, str(kwargs['pk']))
#         return form_page(request, edit_flag_form(), data=data['flag'])
#
#     def post(self, request, **kwargs):
#         response, status_code = put_flag(request, str(kwargs['pk']), request.POST)
#         if status_code != 200:
#             return form_page(request, edit_flag_form(), data=request.POST, errors=response.get('errors'))
#
#         return redirect(reverse_lazy('flags:flags'))
#
#
# class ViewFlag(TemplateView):
#     def get(self, request, **kwargs):
#         data, status_code = get_flag(request, str(kwargs['pk']))
#
#         context = {
#             'data': data,
#             'title': data['flag']['name']
#         }
#         return render(request, 'flags/profile.html', context)
#
#
# class ChangeFlagStatus(TemplateView):
#     def get(self, request, **kwargs):
#         status = kwargs['status']
#         description = ''
#
#         if status != 'deactivate' and status != 'reactivate':
#             raise Http404
#
#         if status == 'deactivate':
#             description = get_string('flags.update_flag.status.deactivate_warning')
#
#         if status == 'reactivate':
#             description = get_string('flags.update_flag.status.reactivate_warning')
#
#         context = {
#             'title': 'Are you sure you want to {} this flag?'.format(status),
#             'description': description,
#             'user_id': str(kwargs['pk']),
#             'status': status,
#         }
#         return render(request, 'flags/change_status.html', context)
#
#     def post(self, request, **kwargs):
#         status = kwargs['status']
#
#         if status != 'deactivate' and status != 'reactivate':
#             raise Http404
#
#         put_flag(request, str(kwargs['pk']), json={'status': request.POST['status']})
#
#         return redirect(reverse_lazy('flags:flags'))
#

picklists/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from core.services import get_countries, get_denial_reasons
from flags.services import get_flags
from lite_forms.generators import form_page
from lite_forms.views import SingleFormView
from picklists.forms import (
    add_picklist_item_form,
    deactivate_picklist_item,
    reactivate_picklist_item,
    add_letter_paragraph_form,
    edit_picklist_item_form,
    edit_letter_paragraph_form,
)
from picklists.services import (
    get_picklists,
    get_picklist_item,
    put_picklist_item,
)
from picklists.validators import validate_and_post_picklist_item, validate_and_put_picklist_item
from teams.services import get_team
from users.services import get_gov_user


class Picklists(TemplateView):
    def get(self, request, **kwargs):
        """
        Return a list of picklists and show all the relevant items
        """
        # Ensure that the page has a type
        picklist_type = request.GET.get("type")
        if not picklist_type:
            return redirect(reverse_lazy("picklists:picklists") + "?type=proviso")
        user, _ = get_gov_user(request)
        team, _ = get_team(request, user["user"]["team"]["id"])
        picklist_items = get_picklists(request, picklist_type, True)

        active_picklist_items = [x for x in picklist_items["picklist_items"] if x["status"]["key"] == "active"]
        deactivated_picklist_items = [x for x in picklist_items["picklist_items"] if x["status"]["key"] != "active"]

        context = {
            "title": "Picklists - " + team["team"]["name"],
            "team": team["team"],
            "active_picklist_items": active_picklist_items,
            "deactivated_picklist_items": deactivated_picklist_items,
            "type": picklist_type,
        }
        return render(request, "teams/picklist.html", context)


class ViewPicklistItem(TemplateView):
    def get(self, request, **kwargs):
        picklist_item = get_picklist_item(request, str(kwargs["pk"]))

        context = {
            "title": picklist_item["name"],
            "picklist_item": picklist_item,
            "activity": picklist_item["activity"],
        }
        return render(request, "teams/picklist-item.html", context)


class AddPicklistItem(SingleFormView):
    def init(self, request, **kwargs):
        self.action = validate_and_post_picklist_item
        countries, _ = get_countries(request)
        flags, _ = get_flags(request)
        denial_reasons, _ = get_denial_reasons(request, False, False)

        self.context = {**countries, **flags, **denial_reasons}
        self.success_url = reverse_lazy("picklists:picklists") + "?type=" + self.request.GET.get("type")

    def get_form(self):
        if self.request.GET.get("type") == "letter_paragraph":
            return add_letter_paragraph_form(self.request.GET.get("type"))
        else:
            return add_picklist_item_form(self.request.GET.get("type"))


class EditPicklistItem(SingleFormView):
    def init(self, request, **kwargs):
        self.object_pk = kwargs["pk"]
        self.object = get_picklist_item(request, self.object_pk)
        self.action = validate_and_put_picklist_item
        self.success_url = reverse_lazy("picklists:picklist_item", kwargs={"pk": self.object_pk})
        countries, _ = get_countries(request)
        flags, _ = get_flags(request)
        denial_reasons, _ = get_denial_reasons(request, False, False)

        self.context = {**countries, **flags, **denial_reasons}

    def get_form(self):
        if self.object["type"]["key"] == "letter_paragraph":
            return edit_letter_paragraph_form(self.object)
        else:
            return edit_picklist_item_form(self.object)


class DeactivatePicklistItem(TemplateView):
    picklist_item_id = None
    picklist_item = None
    form = None

    def dispatch(self, request, *args, **kwargs):
        self.picklist_item_id = str(kwargs["pk"])
        self.picklist_item = get_picklist_item(request, self.picklist_item_id)
        self.form = deactivate_picklist_item(self.picklist_item)

        return super(DeactivatePicklistItem, self).dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        if self.picklist_item["status"]["key"] == "deactivated":
            raise Http404

        return form_page(request, self.form)

    def post(self, request, **kwargs):
        data = {"status": "deactivated"}

        put_picklist_item(request, self.picklist_item_id, data)
        return redirect(reverse_lazy("picklists:picklist_item", kwargs={"pk": self.picklist_item["id"]}))


class ReactivatePicklistItem(TemplateView):
    picklist_item_id = None
    picklist_item = None
    form = None

    def dispatch(self, request, *args, **kwargs):
        self.picklist_item_id = str(kwargs["pk"])
        self.picklist_item = get_picklist_item(request, self.picklist_item_id)
        self.form = reactivate_picklist_item(self.picklist_item)

        return super(ReactivatePicklistItem, self).dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        if self.picklist_item["status"]["key"] != "deactivated":
            raise Http404

        return form_page(request, self.form)

    def post(self, request, **kwargs):
        data = {"status": "active"}

        put_picklist_item(request, self.picklist_item_id, data)
        return redirect(reverse_lazy("picklists:picklist_item", kwargs={"pk": self.picklist_item["id"]}))

teams/views.py
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, RedirectView

from lite_content.lite_internal_frontend.teams import TeamsPage
from lite_forms.views import SingleFormView
from teams.forms import add_team_form, edit_team_form
from teams.services import get_team, get_teams, post_teams, get_users_by_team, put_team
from users.services import get_gov_user


class TeamsList(TemplateView):
    def get(self, request, **kwargs):
        data, _ = get_teams(request)

        context = {
            "data": data,
        }
        return render(request, "teams/index.html", context)


class Team(RedirectView):
    def get_redirect_url(self):
        user, _ = get_gov_user(self.request)
        return reverse_lazy("teams:team", kwargs={"pk": user["user"]["team"]["id"]})


class TeamDetail(TemplateView):
    def get(self, request, **kwargs):
        user, _ = get_gov_user(self.request)
        team, _ = get_team(request, str(kwargs["pk"]))
        users, _ = get_users_by_team(request, str(kwargs["pk"]))

        context = {
            "team": team["team"],
            "users": users["users"],
            "is_user_in_team": user["user"]["team"]["id"] == team["team"]["id"],
        }
        return render(request, "teams/team.html", context)


class AddTeam(SingleFormView):
    def init(self, request, **kwargs):
        self.form = add_team_form()
        self.action = post_teams

    def get_success_url(self):
        messages.success(self.request, TeamsPage.SUCCESS_MESSAGE)
        return reverse("teams:teams")


class EditTeam(SingleFormView):
    def init(self, request, **kwargs):
        self.object_pk = kwargs["pk"]
        team, _ = get_team(request, self.object_pk)
        self.form = edit_team_form()
        self.data = team["team"]
        self.action = put_team
        self.success_url = reverse("teams:teams")

templates/teams/index.html
{% extends 'layouts/base.html' %}

{% block back_link %}{% endblock %}

{% block body %}
	{% include 'includes/messages.html' %}

	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h1 class="govuk-heading-l">
				{% block title %}
					{% lcs 'teams.TeamsPage.TITLE' %}
				{% endblock %}
			</h1>
		</div>
		<div class="lite-app-bar__controls">
			<a href="{% url 'teams:add' %}" class="govuk-button" draggable="false" role="button">
				{% lcs 'teams.TeamsPage.ADD_A_TEAM_BUTTON' %}
			</a>
		</div>
	</div>

	<table class="govuk-table">
		<thead class="govuk-table__head">
			<tr class="govuk-table__row">
				<th class="govuk-table__header" scope="col">{% lcs 'teams.TeamsPage.Table.NAME' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'teams.TeamsPage.Table.ACTIONS' %}</th>
			</tr>
		</thead>
		<tbody class="govuk-table__body">
			{% for team in data.teams %}
				<tr class="govuk-table__row" id="row-{{ forloop.counter }}">
					<td class="govuk-table__cell">
						<span class="govuk-table__header" aria-hidden="true">{% lcs 'teams.TeamsPage.Table.NAME' %}</span>
						<a href="{% url 'teams:team' team.id %}" class="govuk-link">
							{{ team.name }}
						</a>
					</td>
					<td class="govuk-table__cell">
						{% if not team.id|is_system_team %}
							<span class="govuk-table__header" aria-hidden="true">{% lcs 'teams.TeamsPage.Table.ACTIONS' %}</span>
							<a href="{% url 'teams:edit' team.id %}" class="govuk-link">
								{% lcs 'teams.TeamsPage.Table.EDIT' %}
							</a>
						{% endif %}
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/teams/own_team.html
{% extends 'layouts/base.html' %}

{% block back_link %}{% endblock %}

{% block body %}
	<h1 class="govuk-heading-l">{{ team.name }}</h1>

	<div class="lite-tabs__container">
		<div class="lite-tabs">
			<a href="{% url 'teams:team' %}" class="lite-tabs__tab lite-tabs__tab--selected">Users</a>
			<a href="{% url 'picklists:picklists' %}" class="lite-tabs__tab">Picklists</a>
		</div>
		<div class="lite-tabs__controls">
			<a id="button-invite-user" href="{% url 'users:add' %}" class="govuk-button" draggable="false" role="button">
				{% lcs 'Users.INVITE' %}
			</a>
		</div>
	</div>

	{% if users %}
		<table class="govuk-table">
			<thead class="govuk-table__head">
				<tr class="govuk-table__row">
					<th class="govuk-table__header" scope="col">Name</th>
					<th class="govuk-table__header" scope="col">Email</th>
					<th class="govuk-table__header" scope="col">Status</th>
                    <th class="govuk-table__header" scope="col"></th>
				</tr>
			</thead>
			<tbody class="govuk-table__body">
				{% for user in users %}
                <tr class="govuk-table__row" {% if not user.first_name %}style="background-color: rgba(40, 161, 151, 0.025);"{% endif %}>
                    <td class="govuk-table__cell">
						{% if user.first_name %}
							<a href="{% url 'users:user' user.id %}" style="margin: 0;" class="govuk-link govuk-link--no-visited-state">
								{{ user.first_name }} {{ user.last_name }}
							</a>
						{% else %}
							<strong class="govuk-tag govuk-phase-banner__content__tag ">
								Pending
							</strong>
						{% endif %}
                    </td>
                    <td class="govuk-table__cell">{{ user.email }}</td>
                    <td class="govuk-table__cell">{{ user.status }}</td>
                    <td class="govuk-table__cell">
                        <a href="{% url 'users:edit' user.id %}" style="margin: 0;" class="govuk-link govuk-link--no-visited-state">Edit</a>
                    </td>
                </tr>
            {% endfor %}
			</tbody>
		</table>
	{% else %}
		<p class="govuk-caption-l">You don't have any users at the moment.</p>
	{% endif %}
{% endblock %}

templates/teams/picklist-item.html
{% extends 'layouts/base.html' %}

{% load variable_highlight %}

{% block back_link %}
	<a href="{% url 'picklists:picklists' %}?type={{ picklist_item.type.key }}" class="govuk-back-link">Back to picklist</a>
{% endblock %}

{% block body %}
	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h1 class="govuk-heading-l">{{ picklist_item.name }}</h1>
		</div>
		<div class="lite-app-bar__controls">
			<a href="{% url 'picklists:edit' picklist_item.id %}" role="button" draggable="false" class="govuk-button" data-module="govuk-button">
				Edit item
			</a>
		</div>
	</div>

	{% if picklist_item.status.key == 'deactivated' %}
		<p class="lite-tag lite-tag--small">Deactivated</p>
	{% endif %}

	<p class="govuk-body">
		<span class="govuk-caption-m">Created by</span>
		<a class="govuk-link govuk-link--no-visited-state" href="{% url 'teams:team' picklist_item.team %}">{{ picklist_item.team_name }}</a>
		<span class="govuk-caption-m">-</span>
		<a class="govuk-link govuk-link--no-visited-state" href="{% url 'picklists:picklists' %}?type={{ picklist_item.type.key }}">{{ picklist_item.type.value }}</a>
		<span class="govuk-caption-m">- Last updated</span>
		<span class="govuk-visually-hidden"> on </span>
		{{ picklist_item.updated_at|str_date }}
	</p>

	<br>

	<p class="govuk-body">
		{% if picklist_item.type.key == "letter_paragraph" %}
			{{ picklist_item.text|variable_highlight|linebreaksbr }}
		{% else %}
			{{ picklist_item.text|linebreaksbr }}
		{% endif %}
	</p>

	{% if activity %}
		<div class="govuk-accordion app-accordion" data-module="govuk-accordion" id="accordion-default">
			<div class="govuk-accordion__section">
				<div class="govuk-accordion__section-header">
					<h2 class="govuk-accordion__section-heading">
						<span class="govuk-accordion__section-button" id="accordion-default-heading">
							{% lcs 'CASE_ENTITIES_ACTIVITY' %}
						</span>
					</h2>
				</div>
				<div id="accordion-default-content" class="govuk-accordion__section-content" aria-labelledby="accordion-default-heading">
					{% include "includes/audit-trail.html" %}
				</div>
			</div>
		</div>
	{% endif %}
{% endblock %}

templates/teams/picklist.html
{% extends 'layouts/base.html' %}

{% block back_link %}{% endblock %}

{% block title %}
	{% lcs 'teams.TeamPage.Tabs.PICKLISTS' %} - {{ team.name }}
{% endblock %}

{% block body %}
	<h1 class="govuk-heading-l">{{ team.name }}</h1>

	<div class="lite-tabs__container">
		<div class="lite-tabs">
			<a href="{% url 'teams:team' %}" class="lite-tabs__tab">{% lcs 'teams.TeamPage.Tabs.MEMBERS' %}</a>
			<p class="lite-tabs__tab lite-tabs__tab--selected">{% lcs 'teams.TeamPage.Tabs.PICKLISTS' %}</p>
		</div>
		<div class="lite-tabs__controls">
			<a href="{% url 'picklists:add' %}?type={{ type }}" role="button" draggable="false" class="govuk-button" data-module="govuk-button">
				Add an item
			</a>
		</div>
	</div>

	<div class="govuk-grid-row">
		<div class="govuk-grid-column-one-quarter">
			<ul class="lite-subnav">
				<li class="lite-subnav__link {{ 'proviso'|add_subnav_selected_class:request.get_full_path }}">
					<a class="govuk-link govuk-link--no-visited-state" href="{% url 'picklists:picklists' %}?type=proviso">{% lcs 'picklists.PicklistCategory.PROVISO' %}</a>
				</li>
				<li class="lite-subnav__link {{ 'ecju_query'|add_subnav_selected_class:request.get_full_path }}">
					<a class="govuk-link govuk-link--no-visited-state" href="{% url 'picklists:picklists' %}?type=ecju_query">{% lcs 'picklists.PicklistCategory.STANDARD_ECJU_QUERIES' %}</a>
				</li>
				<li class="lite-subnav__link {{ 'pre_visit_questionnaire'|add_subnav_selected_class:request.get_full_path }}">
					<a class="govuk-link govuk-link--no-visited-state" href="{% url 'picklists:picklists' %}?type=pre_visit_questionnaire">{% lcs 'picklists.PicklistCategory.PRE_VISIT_QUESTIONNAIRES' %}</a>
				</li>
				<li class="lite-subnav__link {{ 'compliance_actions'|add_subnav_selected_class:request.get_full_path }}">
					<a class="govuk-link govuk-link--no-visited-state" href="{% url 'picklists:picklists' %}?type=compliance_actions">{% lcs 'picklists.PicklistCategory.COMPLIANCE_ACTIONS' %}</a>
				</li>
				<li class="lite-subnav__link {{ 'letter_paragraph'|add_subnav_selected_class:request.get_full_path }}">
					<a class="govuk-link govuk-link--no-visited-state" href="{% url 'picklists:picklists' %}?type=letter_paragraph">{% lcs 'picklists.PicklistCategory.LETTER_PARAGRAPHS' %}</a>
				</li>
				<li class="lite-subnav__link {{ 'report_summary'|add_subnav_selected_class:request.get_full_path }}">
					<a class="govuk-link govuk-link--no-visited-state" href="{% url 'picklists:picklists' %}?type=report_summary">{% lcs 'picklists.PicklistCategory.REPORT_SUMMARIES' %}</a>
				</li>
				<li class="lite-subnav__link {{ 'standard_advice'|add_subnav_selected_class:request.get_full_path }}">
					<a class="govuk-link govuk-link--no-visited-state" href="{% url 'picklists:picklists' %}?type=standard_advice">{% lcs 'picklists.PicklistCategory.STANDARD_ADVICE' %}</a>
				</li>
				<li class="lite-subnav__link {{ 'footnotes'|add_subnav_selected_class:request.get_full_path }}">
					<a class="govuk-link govuk-link--no-visited-state" href="{% url 'picklists:picklists' %}?type=footnotes">{% lcs 'picklists.PicklistCategory.FOOTNOTES' %}</a>
				</li>
			</ul>
		</div>
		<div class="govuk-grid-column-three-quarters">
			<div>
				{% if active_picklist_items or deactivated_picklist_items %}
					<div>
						{% for picklist_item in active_picklist_items %}
							{% include 'includes/picklist-item.html' %}
						{% endfor %}
					</div>
					{% if deactivated_picklist_items %}
						<div>
							<h4 class="govuk-heading-s">Deactivated</h4>
							<hr class="lite-horizontal-separator">
							{% for picklist_item in deactivated_picklist_items %}
								{% include 'includes/picklist-item.html' %}
							{% endfor %}
						</div>
					{% endif %}
				{% else %}
					<p class="govuk-caption-l"></p>
					{% include "includes/information-text.html" with text="There aren't any items in this picklist" %}
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

templates/teams/team.html
{% extends 'layouts/base.html' %}

{% block back_link %}
	{% if not is_user_in_team %}
		<a href="{% url 'teams:teams' %}" class="govuk-back-link">{% lcs 'teams.TeamPage.BACK_LINK' %}</a>
	{% endif %}
{% endblock %}

{% block title %}
	{% lcs 'teams.TeamPage.Tabs.MEMBERS' %} - {{ team.name }}
{% endblock %}

{% block body %}
	<h1 class="govuk-heading-l">
		{{ team.name }}
	</h1>

	{% if is_user_in_team %}
		<div class="lite-tabs__container">
			<div class="lite-tabs">
				<p class="lite-tabs__tab lite-tabs__tab--selected">{% lcs 'teams.TeamPage.Tabs.MEMBERS' %}</p>
				<a href="{% url 'picklists:picklists' %}" class="lite-tabs__tab">{% lcs 'teams.TeamPage.Tabs.PICKLISTS' %}</a>
			</div>
			<div class="lite-tabs__controls">
				<a id="button-add-user" href="{% url 'users:add' %}" class="govuk-button" draggable="false" role="button">
					{% lcs 'teams.TeamPage.ADD_A_MEMBER_BUTTON' %}
				</a>
			</div>
		</div>
	{% endif %}

	{% if users %}
		<table class="govuk-table">
			<thead class="govuk-table__head">
				<tr class="govuk-table__row">
					<th class="govuk-table__header" scope="col">{% lcs 'teams.TeamPage.Table.NAME' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'teams.TeamPage.Table.EMAIL' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'teams.TeamPage.Table.STATUS' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'teams.TeamPage.Table.ACTIONS' %}</th>
				</tr>
			</thead>
			<tbody class="govuk-table__body">
				{% for user in users %}
					<tr class="govuk-table__row" id="row-{{ forloop.counter }}">
						<td class="govuk-table__header" scope="row">
							{% if user.first_name %}
								{{ user.first_name }} {{ user.last_name }}
							{% else %}
								<strong class="govuk-tag govuk-tag--blue">
									{% lcs 'teams.TeamPage.Table.PENDING' %}
								</strong>
							{% endif %}
						</td>
						<td class="govuk-table__cell" id="{{ user.email }}">{{ user.email }}</td>
						<td class="govuk-table__cell">{{ user.status }}</td>
						<td class="govuk-table__cell">
							<a id="link-{{ user.email }}" href="{% url 'users:user' user.id %}" class="govuk-link govuk-link--no-visited-state">{% lcs 'teams.TeamPage.Table.VIEW' %}</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		{% include "includes/notice.html" with text='teams.TeamPage.NO_CONTENT_NOTICE' %}
	{% endif %}
{% endblock %}