auth/urls.py
from django.urls import path

from auth import views

app_name = "auth"

urlpatterns = [
    path("login/", views.AuthView.as_view(), name="login"),
    path("callback/", views.AuthCallbackView.as_view(), name="callback"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
]

cases/documents/urls.py
from django.urls import path

from cases.documents import views

app_name = 'documents'
urlpatterns = [
    # ex: /flags/ - Add a document to this case
    path('create-document/', views.PickATemplate.as_view(), name='pick_a_template'),
    # ex: /flags/ - Add a document to this case
    path('create-document/generator/', views.CreateDocument.as_view(), name='create'),
    # ex: /flags/ - Add a document to this case
    path('create-document/generator/preview/', views.Preview.as_view(), name='preview'),
    # ex: /help/ - Add a document to this case
    path('create-document/help/', views.Help.as_view(), name='help'),
]

conf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("auth.urls")),
    path("queues/<uuid:queue_pk>/cases/<uuid:pk>/", include("cases.urls")),
    path("flags/", include("flags.urls")),
    path("document-templates/", include("letter_templates.urls")),
    path("organisations/", include("organisations.urls")),
    path("queues/", include("queues.urls")),
    path("team/picklists/", include("picklists.urls")),
    path("team", include("teams.urls")),
    path("users/", include("users.urls")),
]

letter_templates/urls.py
from django.urls import path

from conf.constants import Permission
from core.helpers import decorate_patterns_with_permission
from letter_templates.views import edit, letter_paragraphs, view, create

app_name = "letter_templates"

urlpatterns = [
    path("", view.LetterTemplatesList.as_view(), name="letter_templates"),
    path("<uuid:pk>/", view.LetterTemplateDetail.as_view(), name="letter_template"),
    path("<uuid:pk>/edit/", edit.EditTemplate.as_view(), name="edit"),
    path("<uuid:pk>/edit-paragraphs/", edit.EditParagraphs.as_view(), name="edit_letter_paragraphs"),
    # Create letter templates
    # ex: /letter-templates/add/
    path("add/", create.Add.as_view(), name="add"),
    # ex: /letter-templates/add/letter-paragraphs/
    path("add/letter-paragraphs/", letter_paragraphs.LetterParagraphs.as_view(), name="letter_paragraphs"),
    # ex: /letter-templates/create/
    path("create/", create.Create.as_view(), name="create"),
]

url_patterns = decorate_patterns_with_permission(urlpatterns, Permission.CONFIGURE_TEMPLATES)

letter_templates/views.py
import os

from django.contrib import messages
from django.shortcuts import render, redirect
from django.template import engines
from django.views.generic import TemplateView
from lite_forms.generators import form_page
from lite_forms.submitters import submit_paged_form

from conf import settings
from letter_templates.forms import add_letter_template
from letter_templates.services import get_letter_paragraphs, get_letter_templates, post_letter_templates
from picklists.services import get_picklists


class LetterTemplates(TemplateView):

    def get(self, request, **kwargs):
        context = {
            'letter_templates': get_letter_templates(request)
        }
        return render(request, 'letter_templates/letter_templates.html', context)


class LetterTemplateDetail(TemplateView):

    def get(self, request, **kwargs):
        context = {
            'letter_templates': get_letter_templates(request)
        }
        return render(request, 'letter_templates/letter_templates.html', context)


def generate_preview(request, letter_paragraphs, name, layout, restricted_to):
    letter_paragraphs = get_letter_paragraphs(request, letter_paragraphs)

    print('\n')
    print(letter_paragraphs)
    print('\n')

    django_engine = engines['django']
    template = django_engine.from_string(
        open(os.path.join(settings.LETTER_TEMPLATES_DIRECTORY, 'licence.html'), 'r').read())
    letter_context = {
        'content': '\n'.join([x['text'] for x in letter_paragraphs]),
    }
    preview = template.render(letter_context)

    return render(request, 'letter_templates/preview.html', {
        'preview': preview,
        'name': name,
        'layout': layout,
        'restricted_to': restricted_to,
        'letter_paragraphs': letter_paragraphs
    })


def generate_generator(request, letter_paragraphs, name, layout, restricted_to):
    letter_paragraphs = get_letter_paragraphs(request, letter_paragraphs)
    return render(request, 'letter_templates/generator.html', {'letter_paragraphs': letter_paragraphs,
                                                               'name': name,
                                                               'layout': layout,
                                                               'restricted_to': restricted_to})


class Add(TemplateView):

    def get(self, request, **kwargs):
        return form_page(request, add_letter_template().forms[0])

    def post(self, request, **kwargs):
        response, validated_data = submit_paged_form(request, add_letter_template(), post_letter_templates)

        if response:
            return response

        return generate_generator(request,
                                  letter_paragraphs=[],
                                  name=request.POST.get('name'),
                                  layout=request.POST.get('layout'),
                                  restricted_to=request.POST.getlist('restricted_to'))


class LetterParagraphs(TemplateView):

    def dispatch(self, request, *args, **kwargs):
        data = request.POST.copy()
        name = data.get('name')
        layout = data.get('layout')
        restricted_to = data.getlist('restricted_to')
        action = data.get('action')
        existing_letter_paragraphs = data.getlist('letter_paragraphs')

        if action == 'add_letter_paragraph':
            all_letter_paragraphs = get_picklists(request, 'letter_paragraph')
            context = {
                'name': name,
                'layout': layout,
                'restricted_to': restricted_to,
                'letter_paragraphs': [x for x in all_letter_paragraphs['picklist_items'] if
                                      x['id'] not in existing_letter_paragraphs],
                'existing_letter_paragraphs': existing_letter_paragraphs
            }
            return render(request, 'letter_templates/letter_paragraphs.html', context)
        elif action == 'preview':
            return generate_preview(request,
                                    existing_letter_paragraphs,
                                    name=name,
                                    layout=layout,
                                    restricted_to=restricted_to)
        elif 'delete' in action:
            pk_to_delete = action.split('.')[1]
            existing_letter_paragraphs.remove(pk_to_delete)

        return generate_generator(request,
                                  letter_paragraphs=existing_letter_paragraphs,
                                  name=name,
                                  layout=layout,
                                  restricted_to=restricted_to)


class Preview(TemplateView):
    def post(self, request, **kwargs):
        post_letter_templates(request, request.POST.copy())

        print('\n')
        print(request.POST)
        print('\n')

        messages.success(request, 'The letter template was created successfully')
        return redirect('letter_templates:letter_templates')

letter_templates/views/create.py
from lite_content.lite_internal_frontend import strings
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import TemplateView
from lite_forms.generators import form_page, error_page
from lite_forms.submitters import submit_paged_form

from letter_templates.forms import add_letter_template
from letter_templates.helpers import get_template_content
from letter_templates.services import post_letter_template
from letter_templates.views.letter_paragraphs import get_order_paragraphs_page


class Add(TemplateView):
    def get(self, request, **kwargs):
        return form_page(request, add_letter_template(request).forms[0])

    @staticmethod
    def post(request):
        next_form, _ = submit_paged_form(request, add_letter_template(request), post_letter_template,)

        if next_form:
            return next_form

        template_content = get_template_content(request)
        return get_order_paragraphs_page(request, template_content)


class Create(TemplateView):
    @staticmethod
    def post(request):
        json = request.POST.copy()
        json["letter_paragraphs"] = request.POST.getlist("letter_paragraphs")
        json["case_types"] = request.POST.getlist("case_types[]")
        json["decisions"] = request.POST.getlist("decisions[]")
        response, status_code = post_letter_template(request, json)

        if status_code == 201:
            messages.success(request, strings.LetterTemplates.LetterTemplates.SUCCESSFULLY_CREATED_BANNER)

        else:
            error_messages = []
            errors = response["errors"]
            for field_errors in errors.values():
                for field_error in field_errors:
                    error_messages.append(field_error)

            return error_page(None, "; ".join(error_messages))

        return redirect("letter_templates:letter_templates")

letter_templates/views/edit.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import TemplateView

from cases.services import get_case_types, get_decisions
from lite_forms.components import Option
from lite_forms.generators import form_page
from lite_forms.submitters import submit_single_form

from letter_templates.forms import edit_letter_template
from letter_templates.services import (
    get_letter_template,
    put_letter_template,
    get_letter_paragraphs,
)
from picklists.services import get_picklists


class EditTemplate(TemplateView):
    def get(self, request, **kwargs):
        letter_template = get_letter_template(request, str(kwargs["pk"]))[0]["template"]
        letter_template_case_types = letter_template.pop("case_types") or []
        letter_template_decisions = letter_template.pop("decisions") or []

        letter_template_case_types = [case_type["reference"]["key"] for case_type in letter_template_case_types]
        letter_template.update(case_types=letter_template_case_types)

        letter_template_decisions = [decision["name"]["key"] for decision in letter_template_decisions]
        letter_template.update(decisions=letter_template_decisions)

        case_type_options = [Option(option["key"], option["value"]) for option in get_case_types(request)]
        decision_options = [Option(decision["key"], decision["value"]) for decision in get_decisions(request)[0]]

        return form_page(
            request, edit_letter_template(letter_template, case_type_options, decision_options), data=letter_template
        )

    @staticmethod
    def post(request, **kwargs):
        letter_template_id = str(kwargs["pk"])
        letter_template = get_letter_template(request, letter_template_id)[0]["template"]

        # Override case restrictions to use getlist
        edited_letter_template_data = request.POST.copy()
        edited_letter_template_data["case_types"] = edited_letter_template_data.getlist("case_types[]")
        edited_letter_template_data["decisions"] = edited_letter_template_data.getlist("decisions[]")

        case_type_options = [Option(option["key"], option["value"]) for option in get_case_types(request)]
        decision_options = [Option(decision["key"], decision["value"]) for decision in get_decisions(request)[0]]

        next_form, _ = submit_single_form(
            request,
            edit_letter_template(letter_template, case_type_options, decision_options),
            put_letter_template,
            object_pk=letter_template_id,
            override_data=edited_letter_template_data,
        )

        if next_form:
            return next_form

        return redirect(reverse("letter_templates:letter_template", kwargs={"pk": letter_template_id}))


class EditParagraphs(TemplateView):
    def get(self, request, **kwargs):
        letter_template = get_letter_template(request, str(kwargs["pk"]))[0]["template"]

        if kwargs.get("override_paragraphs"):
            letter_template["letter_paragraphs"] = kwargs.get("override_paragraphs")

        letter_paragraphs = get_letter_paragraphs(request, letter_template["letter_paragraphs"])
        letter_paragraphs = self.sort_letter_paragraphs(letter_paragraphs, letter_template["letter_paragraphs"])

        context = {"letter_template": letter_template, "letter_paragraphs": letter_paragraphs}
        return render(request, "letter-templates/edit-letter-paragraphs.html", context)

    @staticmethod
    def sort_letter_paragraphs(paragraphs, ids):
        """Order a list of letter paragraphs in the same order as a list of IDs."""
        paragraphs_by_id = {p["id"]: p for p in paragraphs}
        return [paragraphs_by_id[id] for id in ids if id in paragraphs_by_id]

    @staticmethod
    def _add_letter_paragraph(request, existing_paragraphs):
        all_letter_paragraphs = get_picklists(request, "letter_paragraph")
        context = {
            "letter_paragraphs": [
                paragraph
                for paragraph in all_letter_paragraphs["picklist_items"]
                if paragraph["id"] not in existing_paragraphs
            ],
            "existing_letter_paragraphs": existing_paragraphs,
        }
        return render(request, "letter-templates/add-letter-paragraphs.html", context)

    def post(self, request, **kwargs):
        letter_template_id = str(kwargs["pk"])
        action = request.POST.get("action")
        existing_paragraphs = request.POST.getlist("letter_paragraphs")

        if action == "add_letter_paragraph":
            return self._add_letter_paragraph(request, existing_paragraphs)

        elif action == "return_to_preview":
            return self.get(request, override_paragraphs=request.POST.getlist("letter_paragraphs"), **kwargs)

        elif "delete" in action:
            pk_to_delete = action.split(".")[1]
            existing_paragraphs.remove(pk_to_delete)
            return self.get(request, override_paragraphs=existing_paragraphs, **kwargs)

        put_letter_template(
            request, letter_template_id, {"letter_paragraphs": request.POST.getlist("letter_paragraphs")}
        )
        return redirect(reverse("letter_templates:letter_template", kwargs={"pk": letter_template_id}))

letter_templates/views/view.py
from django.shortcuts import render
from django.views.generic import TemplateView

from core.helpers import convert_dict_to_query_params
from letter_templates.services import (
    get_letter_templates,
    get_letter_template,
)


class LetterTemplatesList(TemplateView):
    def get(self, request, **kwargs):
        params = {"page": int(request.GET.get("page", 1))}
        data, _ = get_letter_templates(request, convert_dict_to_query_params(params))
        context = {"data": data, "page": params.pop("page")}
        return render(request, "letter-templates/letter-templates.html", context)


class LetterTemplateDetail(TemplateView):
    def get(self, request, **kwargs):
        letter_template_id = str(kwargs["pk"])
        params = convert_dict_to_query_params({"generate_preview": True, "activity": True})
        response, _ = get_letter_template(request, letter_template_id, params=params)
        context = {
            "letter_template": response["template"],
            "preview": response["preview"],
            "activity": response.get("activity", []),
        }
        return render(request, "letter-templates/letter-template.html", context)

templates/letter_templates/generator.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block body %}
    <div class="lite-app-bar">
        <div class="lite-app-bar__content">
            <h2 class="govuk-heading-l">{% block title %}What letter paragraphs do you want to use?{% endblock %}</h2>
            <h4 class="govuk-heading-s govuk-hint">
                <noscript>To re-order paragraphs, you will need to remove and re-add them in the correct order</noscript>
                <span class="lite-js-only">Drag and drop letter paragraphs to reorder.</span>
            </h4>
        </div>
        <div class="lite-app-bar__controls">
            {% if letter_paragraphs %}
                <form action="{% url 'letter_templates:preview' %}" method="post">
                    {% csrf_token %}
                    {% hidden_field 'name' name %}
                    {% for restricted in restricted_to %}
                        {% hidden_field 'restricted_to' restricted %}
                    {% endfor %}
                    {% hidden_field 'layout' layout %}
                    {% for letter_paragraph in letter_paragraphs %}
                        {% hidden_field 'letter_paragraphs' letter_paragraph.id %}
                    {% endfor %}
                    <button class="govuk-button" id="button-preview" type="submit">Preview</button>
                </form>
            {% endif %}
        </div>
    </div>

    <form action="{% url 'letter_templates:letter_paragraphs' %}" method="post">
        {% csrf_token %}
        {% hidden_field 'name' name %}
		{% for restricted in restricted_to %}
			{% hidden_field 'restricted_to' restricted %}
		{% endfor %}
		{% hidden_field 'layout' layout %}

		<div class="app-letter-generator__container">
			<div class="app-letter-generator__controls">
				{% if letter_paragraphs %}
					<div id="standard-advice-list" class="app-sortable">
						{% for letter_paragraph in letter_paragraphs %}
							<div class="app-letter-generator__picklist-item" data-id="{{ letter_paragraph.id }}" data-text="{{ letter_paragraph.text }}">
								{% hidden_field 'letter_paragraphs' letter_paragraph.id %}
								<p class="app-letter-generator__picklist-item-text">{{ letter_paragraph.name }}</p>
								<button type="submit" name="action" value="delete.{{ letter_paragraph.id }}">
									<span class="govuk-visually-hidden">Remove letter paragraph from template</span>
									✕
								</button>
							</div>
						{% endfor %}
					</div>
					<br>
					<button class="lite-button--link" type="submit" name="action" value="add_letter_paragraph">Add another letter paragraph</button>
				{% else %}
					<button class="lite-button--link" type="submit" name="action" value="add_letter_paragraph">Add letter paragraph</button>
				{% endif %}
			</div>
			<div id="preview" class="govuk-body">
				{% for letter_paragraph in letter_paragraphs %}
					<p id="{{ letter_paragraph.id }}">{{ letter_paragraph.text }}</p>
				{% endfor %}
			</div>
		</div>
	</form>

{% endblock %}

{% block javascript %}
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script src="{% static 'javascripts/letter-template-generator.js' %}"></script>
{% endblock %}

templates/letter_templates/letter_template.html
{% extends 'layouts/base.html' %}

{% block back_link %}
	<a href="{% url 'letter_templates:letter_templates' %}" class="govuk-back-link">{% lcs 'LetterTemplates.LetterTemplate.BACK_LINK' %}</a>
{% endblock %}

{% block body %}
	<div class="app-letter-preview__container">
		<div class="lite-app-bar">
			<div class="lite-app-bar__content">
				<h2 class="govuk-heading-l" id="title">{% block title %}{{ letter_template.name }}{% endblock %}</h2>
			</div>
			<div class="lite-app-bar__controls">
				<a id="edit_template" href="{% url 'letter_templates:edit' letter_template.id %}" class="govuk-button govuk-button--secondary">{% lcs 'LetterTemplates.LetterTemplate.EDIT_BUTTON' %}</a>
				<a id="edit_template_paragraphs" href="{% url 'letter_templates:edit_letter_paragraphs' letter_template.id %}" class="govuk-button govuk-button--secondary">{% lcs 'LetterTemplates.LetterTemplate.EDIT_PARAGRAPH_BUTTON' %}</a>
			</div>
		</div>

		<div class="lite-information-board">
			<div class="govuk-grid-row">
				<div class="govuk-grid-column-one-third">
					<h4 class="govuk-heading-s">{% lcs 'LetterTemplates.LetterTemplate.LAYOUT_TITLE' %}</h4>
					<p class="govuk-label" id="layout">
						{{ letter_template.layout.name }}
					</p>
				</div>
				<div class="govuk-grid-column-one-third">
					<h4 class="govuk-heading-s">{% lcs 'LetterTemplates.LetterTemplate.RESTRICTED_TITLE' %}</h4>
					<p class="govuk-label" id="case_types">
						{% for case_type in letter_template.case_types %}{% if not forloop.first %}{% if forloop.last %} and {% else %}, {% endif %}{% endif %}{{ case_type.reference.key|upper }}{% endfor %}
					</p>
				</div>
				<div class="govuk-grid-column-one-third">
					<h4 class="govuk-heading-s">{% lcs 'LetterTemplates.LetterTemplate.DECISIONS_TITLE' %}</h4>
					<p class="govuk-label" id="decisions">
						{% for decision in letter_template.decisions %}{% if not forloop.first %}{% if forloop.last %} and {% else %}, {% endif %}{% endif %}{{ decision.name.value }}{% endfor %}
					</p>
				</div>
			</div>
			<div class="govuk-grid-row">
				<div class="govuk-grid-column-one-third">
					<h4 class="govuk-heading-s">{% lcs 'LetterTemplates.LetterTemplate.CREATED_TITLE' %}</h4>
					<p class="govuk-label" id="created_at">{{ letter_template.created_at|str_date }}</p>
				</div>
				<div class="govuk-grid-column-one-third">
					<h4 class="govuk-heading-s">{% lcs 'LetterTemplates.LetterTemplate.LAST_UPDATE_TITLE' %}</h4>
					<p class="govuk-label" id="last_updated">{{ letter_template.updated_at|str_date }}</p>
				</div>
			</div>
		</div>

		<div class="app-letter-preview__page" id="preview">
			{{ preview|safe }}
		</div>

		<br><br>

		<!-- Activity -->
		{% if activity %}
			<h3 class="govuk-heading-m">
					{% lcs 'CASE_ENTITIES_ACTIVITY' %}
			</h3>

			<div class="app-activity__list">
				{% for audit in activity %}
					<div id="case-activity-{{ audit.id }}" class="app-activity__item">
						<p class="govuk-body">
							<span class="user">{{ audit.user.first_name }} {{ audit.user.last_name }}</span> {{ audit.text }}
						</p>
						{% if audit.additional_text %}
							<div class="app-activity__additional-text">
								{{ audit.additional_text }}
							</div>
						{% endif %}
						<p class="govuk-hint govuk-!-font-size-16">{{ audit.created_at|str_date }}</p>
					</div>
				{% endfor %}
			</div>
		{% endif %}
	</div>

{% endblock %}

templates/letter_templates/letter_templates.html
{% extends 'layouts/base.html' %}

{% block back_link %}{% endblock %}

{% block body %}

	{% include 'includes/messages.html' %}

	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h2 class="govuk-heading-l">{% block title %}{% lcs "DOCUMENT_TEMPLATES_TITLE" %}{% endblock %}</h2>
		</div>
		<div class="lite-app-bar__controls">
			<a href="{% url 'letter_templates:add' %}" class="govuk-button" draggable="false" role="button" id="button-create-a-template">
				{% lcs 'LetterTemplates.LetterTemplates.CREATE_BUTTON' %}
			</a>
		</div>
	</div>

	{% if data.results %}
		<table class="govuk-table">
			<thead class="govuk-table__head">
				<tr class="govuk-table__row">
					<th class="govuk-table__header" scope="col">{% lcs 'LetterTemplates.LetterTemplates.NAME_COLUMN_TITLE' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'LetterTemplates.LetterTemplates.LAYOUT_COLUMN_TITLE' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'LetterTemplates.LetterTemplates.RESTRICTED_COLUMN_TITLE' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'LetterTemplates.LetterTemplates.UPDATED_COLUMN_TITLE' %}</th>
				</tr>
			</thead>
			<tbody class="govuk-table__body">
				{% for letter_template in data.results %}
					<tr class="govuk-table__row">
						<td class="govuk-table__cell">
                            <a href="{% url 'letter_templates:letter_template' letter_template.id %}" id="{{ letter_template.name }}" class="govuk-link">{{ letter_template.name }}</a>
                        </td>
						<td class="govuk-table__cell">
							{{ letter_template.layout.name }}
						</td>
						<td class="govuk-table__cell">
							{% for case_type in letter_template.case_types %}{% if not forloop.first %}{% if forloop.last %} and {% else %}, {% endif %}{% endif %}{{ case_type.reference.key|upper }}{% endfor %}
						</td>
						<td class="govuk-table__cell">
							{{ letter_template.updated_at|str_date }}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
        {% include "includes/pagination.html" with data=data %}
	{% else %}
        {% lcs 'letter_templates.LetterTemplatesPage.NONE_FOUND' as text %}
        {% include "includes/information-text.html" with text=text  %}
	{% endif %}

{% endblock %}

templates/letter_templates/order_letter_paragraphs.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block body %}

    <form action="{% url 'letter_templates:letter_paragraphs' %}" method="post">
        {% csrf_token %}
        {% hidden_field 'name' name %}
        {% for case_type in case_types %}
            {% hidden_field 'case_types[]' case_type %}
        {% endfor %}
		{% for decision in decisions %}
            {% hidden_field 'decisions[]' decision %}
        {% endfor %}
        {% hidden_field 'layout' layout.id %}
        <div class="lite-app-bar">
            <div class="lite-app-bar__content">
                <h2 class="govuk-heading-l">{% block title %}{% lcs 'LetterTemplates.OrderParagraph.TITLE' %}{% endblock %}</h2>
                <h4 class="govuk-heading-s govuk-hint">
                    <noscript>{% lcs 'LetterTemplates.OrderParagraph.NO_JS_HINT' %}</noscript>
                    <span class="lite-js-only">{% lcs 'LetterTemplates.OrderParagraph.JS_HINT' %}</span>
                </h4>
            </div>
            <div class="lite-app-bar__controls">
                <button class="govuk-button" id="button-preview" type="submit" name="action" value="preview">{% lcs 'LetterTemplates.OrderParagraph.PREVIEW_BUTTON' %}</button>
            </div>
        </div>

		<div class="app-letter-generator__container">
			<div class="app-letter-generator__controls">
				{% if letter_paragraphs %}
					<div id="standard-advice-list" class="app-sortable">
						{% for letter_paragraph in letter_paragraphs %}
							<div class="app-letter-generator__picklist-item" data-id="{{ letter_paragraph.id }}" data-text="{{ letter_paragraph.text }}">
								{% hidden_field 'letter_paragraphs' letter_paragraph.id %}
								<p class="app-letter-generator__picklist-item-text">{{ letter_paragraph.name }}</p>
								<button type="submit" name="action" value="delete.{{ letter_paragraph.id }}">
									<span class="govuk-visually-hidden">{% lcs 'LetterTemplates.OrderParagraph.REMOVE_BUTTON' %}</span>
									✕
								</button>
							</div>
						{% endfor %}
					</div>
					<br>
				{% endif %}
                <button class="lite-button--link" type="submit" name="action" value="add_letter_paragraph">{% lcs 'letter_templates.LetterTemplatesPage.ADD_PARAGRAPH' %}</button>
            </div>
			<div id="paragraph-list" class="govuk-body">
				{% for letter_paragraph in letter_paragraphs %}
					<p id="{{ letter_paragraph.id }}">{{ letter_paragraph.text }}</p>
				{% endfor %}
			</div>
		</div>
	</form>

{% endblock %}

{% block javascript %}
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script src="{% static 'javascripts/letter-template-generator.js' %}"></script>
{% endblock %}

templates/letter_templates/preview.html
{% extends 'layouts/base.html' %}

{% block body %}
	<div class="app-letter-preview__container">
		<div class="lite-app-bar">
			<div class="lite-app-bar__content">
				<h2 class="govuk-heading-l">{% block title %}{% lcs 'LetterTemplates.Preview.TITLE' %}{% endblock %}</h2>
			</div>
			<div class="lite-app-bar__controls">
				<form action="{% url 'letter_templates:create' %}" method="post">
					{% csrf_token %}
					{% hidden_field 'name' name %}
					{% for case_type in case_types %}
						{% hidden_field 'case_types[]' case_type %}
					{% endfor %}
					{% for decision in decisions %}
						{% hidden_field 'decisions[]' decision %}
					{% endfor %}
					{% hidden_field 'layout' layout.id %}
					{% for letter_paragraph in letter_paragraphs %}
						{% hidden_field 'letter_paragraphs' letter_paragraph %}
					{% endfor %}
					<button class="govuk-button" type="submit" name="action" value="print">{% lcs 'LetterTemplates.Preview.SAVE_BUTTON' %}</button>
				</form>
			</div>
		</div>

		<div class="app-letter-preview__page" id="preview">
			{{ preview|safe }}
		</div>
	</div>
{% endblock %}