auth/urls.py
from django.urls import path

from auth import views

app_name = "auth"

urlpatterns = [
    path("login/", views.AuthView.as_view(), name="login"),
    path("callback/", views.AuthCallbackView.as_view(), name="callback"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
]

cases/urls.py
from django.urls import path

from cases.views import main, advice, goods, goods_query, ecju, generate_document, destinations
from flags.views import AssignFlags

app_name = "cases"

urlpatterns = [
    path("", main.ViewCase.as_view(), name="case"),
    path("done/", main.CaseImDoneView.as_view(), name="done"),
    path("change-status/", main.ChangeStatus.as_view(), name="manage"),
    path("move/", main.MoveCase.as_view(), name="move"),
    path("additional-contacts/", main.AdditionalContacts.as_view(), name="additional_contacts"),
    path("additional-contacts/add/", main.AddAnAdditionalContact.as_view(), name="add_additional_contact"),
    path("documents/", main.Documents.as_view(), name="documents"),
    path("attach/", main.AttachDocuments.as_view(), name="attach_documents"),
    path("documents/<str:file_pk>/", main.Document.as_view(), name="document"),
    path("assign-flags/", AssignFlags.as_view(), name="assign_flags"),
    path("user-advice-view/", advice.ViewUserAdvice.as_view(), name="user_advice_view"),
    path("team-advice-view/coalesce/", advice.CoalesceUserAdvice.as_view(), name="coalesce_user_advice"),
    path("team-advice-view/", advice.ViewTeamAdvice.as_view(), name="team_advice_view"),
    path("final-advice-view/coalesce/", advice.CoalesceTeamAdvice.as_view(), name="coalesce_team_advice"),
    path("final-advice-view/", advice.ViewFinalAdvice.as_view(), name="final_advice_view"),
    path("advice-view/give-user-advice/", advice.GiveUserAdvice.as_view(), name="give_user_advice"),
    path(
        "advice-view/give-user-advice/<str:type>/",
        advice.GiveUserAdviceDetail.as_view(),
        name="give_user_advice_detail",
    ),
    path("advice-view/give-team-advice/", advice.GiveTeamAdvice.as_view(), name="give_team_advice"),
    path(
        "advice-view/give-team-advice/<str:type>/",
        advice.GiveTeamAdviceDetail.as_view(),
        name="give_team_advice_detail",
    ),
    path("advice-view/give-final-advice/", advice.GiveFinalAdvice.as_view(), name="give_final_advice"),
    path(
        "advice-view/give-final-advice/<str:type>/",
        advice.GiveFinalAdviceDetail.as_view(),
        name="give_final_advice_detail",
    ),
    path("finalise-goods-countries/", advice.FinaliseGoodsCountries.as_view(), name="finalise_goods_countries"),
    path("finalise/", advice.Finalise.as_view(), name="finalise"),
    path("finalise/generate-documents/", advice.FinaliseGenerateDocuments.as_view(), name="finalise_documents"),
    path(
        "finalise/<str:decision_key>/generate-document/select-template/",
        generate_document.SelectTemplateFinalAdvice.as_view(),
        name="finalise_document_template",
    ),
    path(
        "finalise/<str:decision_key>/generate-document/<uuid:tpk>/edit/",
        generate_document.EditTextFinalAdvice.as_view(),
        name="finalise_document_edit_text",
    ),
    path(
        "finalise/<str:decision_key>/generate-document/<uuid:tpk>/add-paragraphs/",
        generate_document.AddDocumentParagraphsFinalAdvice.as_view(),
        name="finalise_document_add_paragraphs",
    ),
    path(
        "finalise/<str:decision_key>/generate-document/<uuid:tpk>/preview/",
        generate_document.PreviewDocument.as_view(),
        name="finalise_document_preview",
    ),
    path(
        "finalise/<str:decision_key>/generate-document/<uuid:tpk>/create/",
        generate_document.CreateDocumentFinalAdvice.as_view(),
        name="finalise_document_create",
    ),
    path("ecju-queries/", ecju.ViewEcjuQueries.as_view(), name="ecju_queries"),
    path("ecju-queries/choose-type", ecju.ChooseECJUQueryType.as_view(), name="choose_ecju_query_type"),
    path("ecju-queries/add", ecju.CreateEcjuQuery.as_view(), name="ecju_queries_add"),
    path("respond-to-clc-query/", goods_query.RespondCLCQuery.as_view(), name="respond_to_clc_query"),
    path("respond-to-clc-query/flags/", goods_query.RespondCLCFlags.as_view(), name="respond_to_clc_query_flags",),
    path(
        "respond-to-pv-grading-query/", goods_query.RespondPVGradingQuery.as_view(), name="respond_to_pv_grading_query",
    ),
    path(
        "respond-to-pv-grading-query/flags/",
        goods_query.RespondPVGradingFlags.as_view(),
        name="respond_to_pv_grading_query_flags",
    ),
    path("review-goods/", goods.ReviewGoods.as_view(), name="review_goods"),
    path("review-goods-clc/", goods.ReviewGoodsClc.as_view(), name="review_goods_clc"),
    path("generate-document/", generate_document.SelectTemplate.as_view(), name="generate_document"),
    path(
        "generate-document/<uuid:tpk>/edit/",
        generate_document.EditDocumentText.as_view(),
        name="generate_document_edit",
    ),
    path(
        "generate-document/<uuid:dpk>/",
        generate_document.RegenerateExistingDocument.as_view(),
        name="generate_document_regenerate",
    ),
    path(
        "generate-document/<uuid:tpk>/add-paragraphs/",
        generate_document.AddDocumentParagraphs.as_view(),
        name="generate_document_add_paragraphs",
    ),
    path(
        "generate-document/<uuid:tpk>/preview/",
        generate_document.PreviewDocument.as_view(),
        name="generate_document_preview",
    ),
    path(
        "generate-document/<uuid:tpk>/create/",
        generate_document.CreateDocument.as_view(),
        name="generate_document_create",
    ),
    path("assign-destination-flags/", destinations.AssignDestinationFlags.as_view(), name="assign_destination_flags",),
    path("case-officer/", main.CaseOfficer.as_view(), name="case_officer"),
    path("assign-user/", main.UserWorkQueue.as_view(), name="assign_user"),
    path("assign-user-queue/<uuid:user_pk>/", main.UserTeamQueue.as_view(), name="assign_user_queue"),
]

conf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("auth.urls")),
    path("queues/<uuid:queue_pk>/cases/<uuid:pk>/", include("cases.urls")),
    path("flags/", include("flags.urls")),
    path("document-templates/", include("letter_templates.urls")),
    path("organisations/", include("organisations.urls")),
    path("queues/", include("queues.urls")),
    path("team/picklists/", include("picklists.urls")),
    path("team", include("teams.urls")),
    path("users/", include("users.urls")),
]

flags/urls.py
from django.urls import path

from flags import views

app_name = "flags"

urlpatterns = [
    path("", views.FlagsList.as_view(), name="flags"),
    path("add/", views.AddFlag.as_view(), name="add"),
    path("rules/", views.ManageFlagRules.as_view(), name="flagging_rules"),
    path("rules/create/", views.CreateFlagRules.as_view(), name="create_flagging_rules"),
    path("rules/<uuid:pk>/edit/", views.EditFlaggingRules.as_view(), name="edit_flagging_rule"),
    path("rules/<uuid:pk>/<str:status>/", views.ChangeFlaggingRuleStatus.as_view(), name="change_flagging_rule_status"),
    path("<uuid:pk>/", views.ViewFlag.as_view(), name="flag"),
    path("<uuid:pk>/edit/", views.EditFlag.as_view(), name="edit"),
    path("<uuid:pk>/edit/<str:status>/", views.ChangeFlagStatus.as_view(), name="change_status"),
]

organisations/urls.py
from django.urls import path

from flags.views import AssignFlags
from organisations import views

app_name = "organisations"

urlpatterns = [
    path("", views.OrganisationList.as_view(), name="organisations"),
    path("<uuid:pk>/", views.OrganisationDetails.as_view(), name="organisation"),
    path("<uuid:pk>/members/", views.OrganisationMembers.as_view(), name="organisation_members"),
    path("<uuid:pk>/sites/", views.OrganisationSites.as_view(), name="organisation_sites"),
    path("<uuid:pk>/assign-flags/", AssignFlags.as_view(), name="assign_flags"),
    path("register/", views.RegisterOrganisation.as_view(), name="register"),
    path("<uuid:pk>/edit/", views.EditOrganisation.as_view(), name="edit"),
    path("register-hmrc/", views.RegisterHMRC.as_view(), name="register_hmrc"),
]

cases/forms/additional_contacts.py
from django.urls import reverse_lazy

from core.services import get_countries
from lite_content.lite_internal_frontend.cases import AddAdditionalContact
from lite_forms.common import country_question
from lite_forms.components import Form, TextInput, TextArea, BackLink


def add_additional_contact_form(request, queue_id, case_id):
    return Form(
        title=AddAdditionalContact.TITLE,
        description=AddAdditionalContact.DESCRIPTION,
        questions=[
            TextInput(
                title=AddAdditionalContact.Details.TITLE,
                description=AddAdditionalContact.Details.DESCRIPTION,
                name="details",
            ),
            TextInput(title=AddAdditionalContact.Name.TITLE, name="name"),
            TextArea(
                title=AddAdditionalContact.Address.TITLE,
                description=AddAdditionalContact.Address.DESCRIPTION,
                name="address",
            ),
            country_question(get_countries(request, True), ""),
            TextInput(title=AddAdditionalContact.Email.TITLE, name="email"),
            TextInput(
                title=AddAdditionalContact.PhoneNumber.TITLE,
                description=AddAdditionalContact.PhoneNumber.DESCRIPTION,
                name="phone_number",
            ),
        ],
        back_link=BackLink(
            AddAdditionalContact.BACK_LINK,
            reverse_lazy("cases:additional_contacts", kwargs={"queue_pk": queue_id, "pk": case_id}),
        ),
        default_button_name=AddAdditionalContact.SUBMIT_BUTTON,
    )

cases/forms/advice.py
from cases.constants import CaseType
from lite_forms.components import Form, RadioButtons, Option, BackLink
from lite_content.lite_internal_frontend.strings import cases


def advice_recommendation_form(post_url, back_url, case_sub_type):
    if case_sub_type == CaseType.OPEN.value:
        denial_option = Option("refuse", cases.AdviceRecommendationForm.RadioButtons.REJECT)
    else:
        denial_option = Option("refuse", cases.AdviceRecommendationForm.RadioButtons.REFUSE)

    return Form(
        cases.AdviceRecommendationForm.TITLE,
        cases.AdviceRecommendationForm.DESCRIPTION,
        [
            RadioButtons(
                "type",
                [
                    Option("approve", cases.AdviceRecommendationForm.RadioButtons.GRANT),
                    Option("proviso", cases.AdviceRecommendationForm.RadioButtons.PROVISO),
                    denial_option,
                    Option("no_licence_required", cases.AdviceRecommendationForm.RadioButtons.NLR),
                    Option("not_applicable", cases.AdviceRecommendationForm.RadioButtons.NOT_APPLICABLE, show_or=True),
                ],
            ),
        ],
        default_button_name=cases.AdviceRecommendationForm.Actions.CONTINUE_BUTTON,
        back_link=BackLink(cases.AdviceRecommendationForm.Actions.BACK_BUTTON, back_url),
        post_url=post_url,
    )

cases/forms/attach_documents.py
from lite_content.lite_internal_frontend.strings import cases
from lite_forms.components import Form, TextArea, FileUpload, BackLink


def attach_documents_form(case_url):
    return Form(
        cases.Manage.Documents.AttachDocuments.TITLE,
        cases.Manage.Documents.AttachDocuments.DESCRIPTION,
        [
            FileUpload(),
            TextArea(
                title=cases.Manage.Documents.AttachDocuments.DESCRIPTION_FIELD_TITLE,
                optional=True,
                name="description",
                extras={"max_length": 280,},
            ),
        ],
        back_link=BackLink(cases.Manage.Documents.AttachDocuments.BACK_TO_CASE_DOCUMENTS, case_url),
    )

cases/views/clc_query.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from lite_forms.components import HiddenField
from lite_forms.generators import form_page
from lite_forms.submitters import submit_single_form

from cases.forms.flags import flags_form
from cases.forms.respond_to_clc_query import respond_to_clc_query_form
from cases.services import (
    get_case,
    put_control_list_classification_query,
    put_flag_assignments,
)
from core.services import get_user_permissions
from flags.services import get_goods_flags
from picklists.services import get_picklist_item


class Respond(TemplateView):
    case = None
    form = None

    def dispatch(self, request, *args, **kwargs):
        case_id = str(kwargs["pk"])
        self.case = get_case(request, case_id)
        self.form = respond_to_clc_query_form(request, self.case)

        permissions = get_user_permissions(request)
        if "REVIEW_GOODS" not in permissions:
            return redirect(reverse_lazy("cases:case", kwargs={"pk": case_id}))

        return super(Respond, self).dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        return form_page(request, self.form)

    def post(self, request, **kwargs):
        # If 'set-flags' take them to the goods flags page
        if request.POST.get("action") == "set-flags":
            form = flags_form(flags=get_goods_flags(request, True), level="goods", origin="response", url="#")

            form.questions.append(HiddenField("is_good_controlled", request.POST["is_good_controlled"]))
            form.questions.append(HiddenField("control_code", request.POST.get("control_code")))
            form.questions.append(HiddenField("report_summary", request.POST["report_summary"]))
            form.questions.append(HiddenField("comment", request.POST["comment"]))

            form.post_url = reverse_lazy("cases:respond_to_clc_query_flags", kwargs={"pk": self.case["id"]})
            return form_page(request, form, data={"flags": self.case["query"]["good"]["flags"]})

        if request.POST.get("action") != "change":
            form_data = request.POST.copy()

            if request.POST.get("report_summary") == "None":
                del form_data["report_summary"]

            response, response_data = submit_single_form(
                request,
                self.form,
                put_control_list_classification_query,
                object_pk=str(self.case["query"]["id"]),
                override_data=form_data,
            )

            if response:
                return response
            response_data = response_data["control_list_classification_query"]
        # If validate only is removed (therefore the user is on the overview page
        # already) go back to the case and show a success message
        if not request.POST.get("validate_only"):
            if request.POST.get("action") == "change":
                return form_page(request, self.form, data=request.POST)

            return redirect(reverse_lazy("cases:case", kwargs={"pk": self.case["id"]}))

        # Remove validate only key and go to overview page
        if response_data["is_good_controlled"] == "no":
            response_data.pop("control_code")

        context = {
            "title": "Response Overview",
            "data": response_data,
            "case": self.case,
        }

        if response_data.get("report_summary"):
            context["report_summary"] = get_picklist_item(request, response_data["report_summary"])

        return render(request, "case/clc-query-overview.html", context)


class RespondFlags(TemplateView):
    case = None
    form = None

    def dispatch(self, request, *args, **kwargs):
        self.case = get_case(request, str(kwargs["pk"]))
        self.form = flags_form(flags=get_goods_flags(request, True), level="goods", origin="response", url="#")
        self.form.post_url = reverse_lazy("cases:respond_to_clc_query_flags", kwargs={"pk": self.case["id"]})

        return super(RespondFlags, self).dispatch(request, *args, **kwargs)

    def post(self, request, **kwargs):
        put_flag_assignments(
            request,
            {
                "level": "Goods",
                "objects": self.case["query"]["good"]["id"],
                "flags": request.POST.getlist("flags"),
                "note": request.POST.get("note"),
            },
        )

        context = {
            "title": "Response Overview",
            "data": request.POST,
            "case": get_case(request, str(kwargs["pk"])),  # Do another pull of case as case flags have changed
            "report_summary": get_picklist_item(request, request.POST["report_summary"]),
        }
        return render(request, "case/clc-query-overview.html", context)

cases/views/destinations.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from core.helpers import convert_dict_to_query_params


class AssignDestinationFlags(TemplateView):
    def get(self, request, **kwargs):
        case_id = str(kwargs["pk"])

        params = {}
        params["items"] = request.GET.getlist("destinations")
        params["level"] = "destinations"
        post_url = "?" + convert_dict_to_query_params(params)
        return redirect(
            reverse_lazy("cases:assign_flags", kwargs={"queue_pk": kwargs["queue_pk"], "pk": case_id}) + post_url
        )

templates/cases/case/change-status.html
{% extends 'layouts/two_pane.html' %}

{% load humanize %}

{% block back_link %}
	<a href="{% url 'cases:case' case.id %}{{ queue_params }}" class="govuk-back-link">Back</a>
{% endblock %}

{% block body %}

	<h2 class="govuk-heading-l">{{ title }}</h2>

	<form method="post">
		{% csrf_token %}
        <input type="hidden" name="queue" value="{{ queue_params }}"/>
		<div class="govuk-form-group">
            {% if title == 'Manage CLC query case' %}
    			<label class="govuk-label" for="status">
	    			CLC Query Status
		    	</label>
            {% else %}
                <label class="govuk-label" for="status">
	    			Application Status
		    	</label>
            {% endif %}
			<select id="status" class="govuk-select" name="status" id="status">
                {% for status in statuses.statuses %}
				    <option value="{{ status.status }}"
                            {% if data.case.application.status == status.status or data.case.query.status == status.status%}
                                selected
                            {% endif %}>
                        {{ status.status|default:"Untitled"|sentence_case }}
                    </option>
                {% endfor %}
			</select>
		</div>

		<div class="govuk-form-group">
			<button type="submit" class="govuk-button">Save</button>
		</div>
	</form>

{% endblock %}

templates/cases/case/flags.html
{% extends 'layouts/base.html' %}

{% load static humanize %}

{% block back_link %}
	<a href="/cases/{{ caseId }}/" class="govuk-back-link">Back to Case</a>
{% endblock %}

{% block body %}

<h2 class="govuk-heading-l">Assign flags to this case</h2>

<form method="post">

	{% csrf_token %}

	<div class="govuk-form-group">
		<span id="waste-hint" class="govuk-hint">
			Select all that apply.
		</span>
	</div>

	<div class="govuk-form-group">
		<div class="govuk-checkboxes">
			{% for flag in case_level_team_flags %}
				<div class="govuk-checkboxes__item">
					<input {% if flag.selected %} checked {% endif %} class="govuk-checkboxes__input" id="{{ flag.name }}" name="flags[]"
						type="checkbox" value="{{ flag.id }}">
					<label class="govuk-label govuk-checkboxes__label" for="{{ flag.name }}">
						{{ flag.name }}
					</label>
				</div>
			{% endfor %}
		</div>
	</div>

	<button type="submit" class="govuk-button" style="margin: 0;">
		Save
	</button>
</form>

{% endblock %}

templates/cases/case/goods_flags.html
{% extends 'layouts/base.html' %}

{% load static humanize %}

{% block back_link %}
	<a href="/cases/{{ caseId }}/" class="govuk-back-link">Back to Case</a>
{% endblock %}

{% block body %}

<h2 class="govuk-heading-l">Assign flags to this good</h2>

<form method="post">

	{% csrf_token %}

	<div class="govuk-form-group">
		<span id="waste-hint" class="govuk-hint">
			Select all that apply.
		</span>
	</div>

	<div class="govuk-form-group">
		<div class="govuk-checkboxes">
			{% for flag in good_level_team_flags %}
				<div class="govuk-checkboxes__item">
					<input {% if flag.selected %} checked {% endif %} class="govuk-checkboxes__input" id="{{ flag.name }}" name="flags[]"
						type="checkbox" value="{{ flag.id }}">
					<label class="govuk-label govuk-checkboxes__label" for="{{ flag.name }}">
						{{ flag.name }}
					</label>
				</div>
			{% endfor %}
		</div>
	</div>

	<button type="submit" class="govuk-button" style="margin: 0;">
		Save
	</button>
</form>

{% endblock %}

templates/cases/case/index.html
{% extends 'layouts/base.html' %}

{% load humanize %}

{% block back-link %}
	<a href="{% url 'cases:cases' %}" class="govuk-back-link">Back to Cases</a>
{% endblock %}

{% block body %}

<h1 class="govuk-heading-l">{{ title }}</h1>
<a role="button" draggable="false" class="govuk-button" href="{% url 'cases:move' data.case.id %}">
	{% get_string 'cases.manage.move_case.button' %}
</a>
<a role="button" draggable="false" class="govuk-button" href="{% url 'cases:manage' data.case.id %}">
	Progress Application
</a>
<a role="button" draggable="false" class="govuk-button" href="{% url 'cases:decide' data.case.id %}">
	Record Decision
</a>

<div class="lite-information-board">
	<div class="govuk-grid-row">
		<div class="govuk-grid-column-one-third">
			<div style="height: auto;">
				<h4 class="lite-heading-s">Applicant</h4>
				<a class="govuk-label govuk-link govuk-link--no-visited-state" href="{% url 'organisations:organisation' data.case.application.organisation.id %}">
					{{ data.case.application.organisation.name }}
				</a>
			</div>
		</div>
		<div class="govuk-grid-column-one-third">
			<div style="height: auto;">
				<h4 class="lite-heading-s">Activity</h4>
				<p class="govuk-label">
					{{ data.case.application.activity }}
				</p>
			</div>
		</div>
		<div class="govuk-grid-column-one-third">
			<div style="height: auto;">
				<h4 class="lite-heading-s">Created at</h4>
				<p class="govuk-label">
					{{ data.case.application.created_at|str_date }}
				</p>
			</div>
		</div>
	</div>

	<div class="govuk-grid-row">
		<div class="govuk-grid-column-one-third">
			<div style="height: auto;">
				<h4 class="lite-heading-s">Reference Number</h4>
				<p class="govuk-label">
					{{ data.case.application.organisation.reference_number_on_information_form|default:'None' }}
				</p>
			</div>
		</div>
		<div class="govuk-grid-column-one-third">
			<div style="height: auto;">
				<h4 class="lite-heading-s">Licence Type</h4>
				<p class="govuk-label">
					{{ data.case.application.licence_type|sentence_case }}
				</p>
			</div>
		</div>
		<div class="govuk-grid-column-one-third">
			<div style="height: auto;">
				<h4 class="lite-heading-s">Last Updated</h4>
				<p class="govuk-label">
					{{ data.case.application.last_modified_at|str_date }}
				</p>
			</div>
		</div>
	</div>
</div>

{% if data.case.application.application_denial_reason %}
<h3 class="govuk-heading-m">Denial Reasons</h3>
{% for reason in data.case.application.application_denial_reason %}
<p class="govuk-heading-s">This case was denied because</p>
{% for reason_id in reason.reasons %}
<p class="govuk-label">{{ reason_id.id }}</p>
{% endfor %}
{% if reason.reason_details %}
<br />
<p class="govuk-heading-s">Further information</p>
<p class="govuk-label">{{ reason.reason_details }}</p>
{% endif %}
{% endfor %}
<br /><br />
{% endif %}

<!-- <div class="lite-tabs--fade">
	<div class="lite-tabs">
		<a class="lite-tabs__tab">Goods</a>
		<a class="lite-tabs__tab">Destinations</a>
		<a class="lite-tabs__tab selected" id="activity">Activity</a>
	</div>
</div> -->

{% include "cases/case/tabs/activity.html" %}

{% endblock %}