auth/urls.py
from django.urls import path

from auth import views

app_name = "auth"

urlpatterns = [
    path("login/", views.AuthView.as_view(), name="login"),
    path("callback/", views.AuthCallbackView.as_view(), name="callback"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
]

conf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("auth.urls")),
    path("queues/<uuid:queue_pk>/cases/<uuid:pk>/", include("cases.urls")),
    path("flags/", include("flags.urls")),
    path("document-templates/", include("letter_templates.urls")),
    path("organisations/", include("organisations.urls")),
    path("queues/", include("queues.urls")),
    path("team/picklists/", include("picklists.urls")),
    path("team", include("teams.urls")),
    path("users/", include("users.urls")),
]

flags/urls.py
from django.urls import path

from flags import views

app_name = "flags"

urlpatterns = [
    path("", views.FlagsList.as_view(), name="flags"),
    path("add/", views.AddFlag.as_view(), name="add"),
    path("rules/", views.ManageFlagRules.as_view(), name="flagging_rules"),
    path("rules/create/", views.CreateFlagRules.as_view(), name="create_flagging_rules"),
    path("rules/<uuid:pk>/edit/", views.EditFlaggingRules.as_view(), name="edit_flagging_rule"),
    path("rules/<uuid:pk>/<str:status>/", views.ChangeFlaggingRuleStatus.as_view(), name="change_flagging_rule_status"),
    path("<uuid:pk>/", views.ViewFlag.as_view(), name="flag"),
    path("<uuid:pk>/edit/", views.EditFlag.as_view(), name="edit"),
    path("<uuid:pk>/edit/<str:status>/", views.ChangeFlagStatus.as_view(), name="change_status"),
]

cases/forms/change_status.py
from cases.helpers import case_view_breadcrumbs
from lite_content.lite_internal_frontend import cases
from lite_forms.components import Form, Option, Select


def change_status_form(queue, case, statuses):
    return Form(
        title=cases.ChangeStatusPage.TITLE,
        description=cases.ChangeStatusPage.DESCRIPTION,
        questions=[
            Select(
                name="status",
                options=[Option(status["key"], status["value"]) for status in statuses],
                include_default_select=False,
            )
        ],
        back_link=case_view_breadcrumbs(queue, case, cases.ChangeStatusPage.TITLE),
    )

cases/forms/flags.py
from cases.helpers import case_view_breadcrumbs
from lite_content.lite_internal_frontend.flags import SetCaseFlagsForm, SetGenericFlagsForm
from lite_forms.components import Form, Filter, Checkboxes, TextArea, BackLink


def flags_form(flags, level, origin, url):
    return Form(
        title=SetGenericFlagsForm.TITLE,
        description=SetGenericFlagsForm.DESCRIPTION,
        questions=[
            Filter(placeholder=SetGenericFlagsForm.Filter.PLACEHOLDER),
            Checkboxes(name="flags", options=flags),
            TextArea(
                name="note",
                title=SetGenericFlagsForm.Note.TITLE,
                description=SetGenericFlagsForm.Note.DESCRIPTION + level,
                optional=True,
            ),
        ],
        javascript_imports=["/assets/javascripts/filter-checkbox-list.js"],
        back_link=BackLink(SetGenericFlagsForm.BACK + origin, url),
    )


def set_case_flags_form(queue, flags, case):
    return Form(
        title=SetCaseFlagsForm.TITLE,
        description=SetCaseFlagsForm.DESCRIPTION,
        questions=[
            Filter(placeholder=SetCaseFlagsForm.Filter.PLACEHOLDER),
            Checkboxes(name="flags", options=flags),
            TextArea(
                name="note",
                title=SetCaseFlagsForm.Note.TITLE,
                description=SetCaseFlagsForm.Note.DESCRIPTION,
                optional=True,
            ),
        ],
        javascript_imports=["/assets/javascripts/filter-checkbox-list.js"],
        back_link=case_view_breadcrumbs(queue, case, SetCaseFlagsForm.TITLE),
    )

flags/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from cases.forms.flags import flags_form, set_case_flags_form
from cases.services import put_flag_assignments, get_good, get_goods_type, get_case, get_destination
from conf.constants import FlagLevels, Permission
from core.helpers import convert_dict_to_query_params, get_params_if_exist
from core.services import get_user_permissions
from flags.forms import (
    add_flag_form,
    edit_flag_form,
    create_flagging_rules_formGroup,
    select_condition_and_flag,
    _levels,
    deactivate_or_activate_flagging_rule_form,
)
from flags.services import (
    get_cases_flags,
    get_goods_flags,
    get_organisation_flags,
    get_destination_flags,
    get_flagging_rules,
    put_flagging_rule,
    get_flagging_rule,
    post_flagging_rules,
)
from flags.services import get_flags, post_flags, get_flag, put_flag
from lite_content.lite_internal_frontend import strings, flags
from lite_content.lite_internal_frontend.flags import UpdateFlag
from lite_forms.components import Option, FiltersBar, Select, Checkboxes
from lite_forms.generators import form_page
from lite_forms.views import MultiFormView, SingleFormView
from organisations.services import get_organisation
from users.services import get_gov_user


class FlagsList(TemplateView):
    def get(self, request, **kwargs):
        data, _ = get_flags(request)
        user_data, _ = get_gov_user(request, str(request.user.lite_api_user_id))

        status = request.GET.get("status", "active")

        if status == "active":
            status = "no_deactivated"
            flags_data = []
            for flag in data["flags"]:
                if flag["status"] == "Deactivated":
                    status = "active"
                if flag["status"] == "Active":
                    flags_data.append(flag)
            data["flags"] = flags_data

        filters = FiltersBar(
            [
                Checkboxes(
                    name="status",
                    options=[Option("deactivated", flags.FlagsList.INCLUDE_DEACTIVATED)],
                    classes=["govuk-checkboxes--small"],
                ),
            ]
        )

        context = {
            "data": data,
            "status": status,
            "user_data": user_data,
            "filters": filters,
        }
        return render(request, "flags/index.html", context)


class AddFlag(SingleFormView):
    def init(self, request, **kwargs):
        self.form = add_flag_form()
        self.action = post_flags

    def get_success_url(self):
        messages.success(self.request, flags.FlagsList.SUCCESS_MESSAGE)
        return reverse("flags:flags")


class EditFlag(SingleFormView):
    def init(self, request, **kwargs):
        self.object_pk = str(kwargs["pk"])
        flag, _ = get_flag(request, self.object_pk)
        self.form = edit_flag_form()
        self.data = flag["flag"]
        self.action = put_flag
        self.success_url = reverse("flags:flags")


class ViewFlag(TemplateView):
    def get(self, request, **kwargs):
        data, _ = get_flag(request, str(kwargs["pk"]))

        context = {"data": data, "title": data["flag"]["name"]}
        return render(request, "flags/profile.html", context)


class ChangeFlagStatus(TemplateView):
    def get(self, request, **kwargs):
        status = kwargs["status"]
        description = ""

        if status != "deactivate" and status != "reactivate":
            raise Http404

        if status == "deactivate":
            description = UpdateFlag.Status.DEACTIVATE_WARNING

        if status == "reactivate":
            description = UpdateFlag.Status.REACTIVATE_WARNING

        context = {
            "title": "Are you sure you want to {} this flag?".format(status),
            "description": description,
            "user_id": str(kwargs["pk"]),
            "status": status,
        }
        return render(request, "flags/change-status.html", context)

    def post(self, request, **kwargs):
        status = kwargs["status"]

        if status != "deactivate" and status != "reactivate":
            raise Http404

        put_flag(request, str(kwargs["pk"]), json={"status": request.POST["status"]})

        return redirect(reverse_lazy("flags:flags"))


class AssignFlags(TemplateView):
    objects = None
    form = None
    selected_flags = None
    url = None
    level = None

    def dispatch(self, request, *args, **kwargs):
        self.objects = request.GET.getlist("items", request.GET.getlist("goods"))

        if not self.objects:
            raise Http404

        self.level = request.GET.get("level")

        kwargs = {"pk": self.objects[0]} if self.level == "organisations" else {"pk": str(kwargs["pk"])}
        origin = request.GET.get("origin", "case")

        if origin == "good":
            kwargs["good_pk"] = self.objects[0]

        # Retrieve the list of flags depending on type
        if self.level == FlagLevels.CASES:
            flags = get_cases_flags(request)
        elif self.level == FlagLevels.GOODS:
            flags = get_goods_flags(request)
        elif self.level == FlagLevels.ORGANISATIONS:
            flags = get_organisation_flags(request)
            origin = "organisation"
        elif self.level == FlagLevels.DESTINATIONS:
            flags = get_destination_flags(request)

        self.url = (
            reverse("organisations:organisation", kwargs=kwargs)
            if self.level == "organisations"
            else reverse("cases:" + origin, kwargs=kwargs)
        )

        # Perform pre-population of the flags if there is only one object to be flagged
        if len(self.objects) == 1:
            self._single_item_processing(request, flags)

        if origin == "review_goods":
            origin = "review good"
            parameters = {"goods": self.objects}
            objects_url_suffix = "?" + convert_dict_to_query_params(parameters)

            self.url += objects_url_suffix

        flags = [Option(flag["id"], flag["name"]) for flag in flags]

        self.form = flags_form(flags=flags, level=self.level, origin=origin, url=self.url)

        if self.level == FlagLevels.CASES:
            case = get_case(request, kwargs["pk"])
            self.form = set_case_flags_form(flags, case)

        return super(AssignFlags, self).dispatch(request, *args, **kwargs)

    def _single_item_processing(self, request, flags):
        object_flags = None
        if self.level == FlagLevels.GOODS:
            obj, status_code = get_good(request, self.objects[0])
            if status_code == 404:
                obj, _ = get_goods_type(request, self.objects[0])
        elif self.level == FlagLevels.CASES:
            obj = {"case": get_case(request, self.objects[0])}
        elif self.level == FlagLevels.ORGANISATIONS:
            obj = get_organisation(request, self.objects[0])
            object_flags = obj.get("flags")
        elif self.level == FlagLevels.DESTINATIONS:
            obj = get_destination(request, self.objects[0])

        # Fetches existing flags on the object
        if self.level != "organisations":
            object_flags = obj.get(self.level[:-1]).get("flags")

        flags_list = []
        for flag in flags:
            for object_flag in object_flags:

                # If flag is both on the object and available to the user, show that it is already set
                if flag["id"] in object_flag["id"]:
                    flags_list.append(flag["id"])
                    break

        self.selected_flags = {"flags": flags_list}

    def get(self, request, **kwargs):
        return form_page(request, self.form, data=self.selected_flags)

    def post(self, request, **kwargs):
        data = {
            "level": self.level,
            "objects": self.objects,
            "flags": request.POST.getlist("flags"),
            "note": request.POST.get("note"),
        }

        response, _ = put_flag_assignments(request, data)

        if "errors" in response:
            return form_page(request, self.form, data=request.POST, errors=response["errors"])

        return redirect(self.url)


class ManageFlagRules(TemplateView):
    def get(self, request, **kwargs):
        if Permission.MANAGE_FLAGGING_RULES.value not in get_user_permissions(request):
            return redirect(reverse_lazy("cases:cases"))

        params = {"page": int(request.GET.get("page", 1))}
        params = get_params_if_exist(request, ["only_my_team", "level", "include_deactivated"], params)

        data, _ = get_flagging_rules(request, convert_dict_to_query_params(params))

        filters = FiltersBar(
            [
                Select(name="level", title=strings.FlaggingRules.List.Filter.Type, options=_levels),
                Checkboxes(
                    name="only_my_team",
                    options=[Option("true", strings.FlaggingRules.List.Filter.MY_TEAM_ONLY)],
                    classes=["govuk-checkboxes--small", "govuk-!-margin-top-6"],
                ),
                Checkboxes(
                    name="include_deactivated",
                    options=[Option("true", strings.FlaggingRules.List.Filter.INCLUDE_DEACTIVATED)],
                    classes=["govuk-checkboxes--small", "govuk-!-margin-top-6"],
                ),
            ]
        )

        context = {
            "data": data,
            "page": params.pop("page"),
            "team": get_gov_user(request)[0]["user"]["team"]["id"],
            "filters": filters,
            "params_str": convert_dict_to_query_params(params),
        }
        return render(request, "flags/flagging-rules-list.html", context)


class CreateFlagRules(MultiFormView):
    def init(self, request, **kwargs):

templates/flags/change-status.html
{% extends "layouts/base.html" %}

{% block body %}
	<h1 class="govuk-heading-l">{{ title }}</h1>
	<p class="govuk-caption-m">{{ description }}</p>
	<form method="post">
		<div class="buttons-row">
			{% csrf_token %}
			{% if status == 'reactivate' %}
				<button type="submit" name="status" value="Active" class="govuk-button">Reactivate Flag</button>
			{% else %}
				<button type="submit" name="status" value="Deactivated" class="govuk-button govuk-button--warning">Deactivate Flag</button>
			{% endif %}
			<a href="{% url 'flags:flags' %}" role="button" draggable="false" class="govuk-button govuk-button--secondary">Cancel</a>
		</div>
	</form>
{% endblock %}

templates/flags/change_status.html
{% extends "layouts/base.html" %}

{% block body %}
	<h2 class="govuk-heading-l">{{ title }}</h2>
	<p class="govuk-caption-m">{{ description }}</p>
	<form method="post">
		<div class="buttons-row">
			{% csrf_token %}
			{% if status == 'reactivate' %}
				<button type="submit" name="status" value="Active" class="govuk-button">Reactivate Flag</button>
			{% else %}
				<button type="submit" name="status" value="Deactivated" class="govuk-button govuk-button--warning">Deactivate Flag</button>
			{% endif %}
			<a href="{% url 'flags:flags' %}" role="button" draggable="false" class="govuk-button govuk-button--secondary">Cancel</a>
		</div>
	</form>
{% endblock %}

templates/flags/flagging-rules-list.html
{% extends 'layouts/base.html' %}

{% block back_link %}{% endblock %}

{% block body %}
	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h1 class="govuk-heading-l">
				{% block title %}
					{% lcs 'FlaggingRules.TITLE' %}
				{% endblock %}
			</h1>
			<p class="govuk-caption-m">
				{% lcs 'FlaggingRules.DESCRIPTION' %}
			</p>
		</div>
		<div class="lite-app-bar__controls">
			<a href="{% url 'flags:create_flagging_rules' %}" class="govuk-button" draggable="false" role="button" id="add-a-flag-button">
				{% lcs 'FlaggingRules.CREATE' %}
			</a>
		</div>
	</div>

	{% include "filters.html" %}

	<table class="govuk-table">
		<thead class="govuk-table__head">
			<tr class="govuk-table__row">
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.TEAM' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.TYPE' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.FLAG' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.CONDITION' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.STATUS' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.ACTIONS' %}</th>
			</tr>
		</thead>
		<tbody class="govuk-table__body">
			{% for flagging_rule in data.results %}
				<tr class="govuk-table__row">
					<td class="govuk-table__cell">
						{{ flagging_rule.team.name }}
					</td>
					<td class="govuk-table__cell">
						{{ flagging_rule.level }}
					</td>
					<td class="govuk-table__cell" id="{{ flagging_rule.flag }}">
						{{ flagging_rule.flag_name }}
					</td>
					<td class="govuk-table__cell">
						{{ flagging_rule.matching_value }}
					</td>
					<td class="govuk-table__cell">
						{{ flagging_rule.status }}
					</td>
					<td class="govuk-table__cell govuk-table__cell--tight">
						{% if flagging_rule.team.id == team %}
							<ul class="govuk-table__cell__actions-list">
								<li class="govuk-table__cell__actions-list-item">
									<a href="{% url 'flags:edit_flagging_rule' flagging_rule.id %}" role="button" draggable="false" class="govuk-link govuk-link--no-visited-state">{% lcs 'FlaggingRules.List.EDIT' %}</a>
								</li>
								<li class="govuk-table__cell__actions-list-item">
									{% if flagging_rule.status == 'Active' %}
										<a href="{% url 'flags:change_flagging_rule_status' flagging_rule.id 'Deactivated' %}" role="button" draggable="false" class="govuk-link govuk-link--no-visited-state">{% lcs 'FlaggingRules.List.DEACTIVATE' %}</a>
									{% elif flagging_rule.status == 'Deactivated' %}
										<a href="{% url 'flags:change_flagging_rule_status' flagging_rule.id 'Active' %}" role="button" draggable="false" class="govuk-link govuk-link--no-visited-state">{% lcs 'FlaggingRules.List.REACTIVATE' %}</a>
									{% endif %}
								</li>
							</ul>
						{% endif %}
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% if data.total_pages > 1 %}
		<br>
		<div class="lite-pagination__container ">
			{% for i in data.total_pages|times %}
				<a href="{% url 'flags:flagging_rules' %}?{{ params_str }}&page={{ i }}" class="lite-pagination__item {% if page == i %}lite-pagination__item--selected{% endif %}" id="page-{{ i }}">
					{{ i }}
				</a>
			{% endfor %}
		</div>
	{% endif %}
{% endblock %}

templates/flags/flagging_rules_list.html
{% extends 'layouts/base.html' %}

{% block back_link %}{% endblock %}

{% block body %}
	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h1 class="govuk-heading-l">{% lcs 'FlaggingRules.TITLE' %}</h1>
			<p class="govuk-caption-m">
				{% lcs 'FlaggingRules.DESCRIPTION' %}
			</p>
		</div>
		<div class="lite-app-bar__controls">
			<a href="{% url 'flags:create_flagging_rules' %}" class="govuk-button" draggable="false" role="button" id="add-a-flag-button">
				{% lcs 'FlaggingRules.CREATE' %}
			</a>
		</div>
	</div>

	{% include "filters.html" %}

	<table class="govuk-table">
		<thead class="govuk-table__head">
			<tr class="govuk-table__row">
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.TEAM' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.TYPE' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.FLAG' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.CONDITION' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.STATUS' %}</th>
				<th class="govuk-table__header" scope="col">{% lcs 'FlaggingRules.List.ACTIONS' %}</th>
			</tr>
		</thead>
		<tbody class="govuk-table__body">
			{% for flagging_rule in data.results %}
				<tr class="govuk-table__row">
					<td class="govuk-table__cell">
						{{ flagging_rule.team.name }}
					</td>
					<td class="govuk-table__cell">
						{{ flagging_rule.level }}
					</td>
					<td class="govuk-table__cell" id="{{ flagging_rule.flag }}">
						{{ flagging_rule.flag_name }}
					</td>
					<td class="govuk-table__cell">
						{{ flagging_rule.matching_value }}
					</td>
					<td class="govuk-table__cell">
						{{ flagging_rule.status }}
					</td>
					<td class="govuk-table__cell govuk-table__cell--tight">
						{% if flagging_rule.team.id == team %}
							<ul class="govuk-table__cell__actions-list">
								<li class="govuk-table__cell__actions-list-item">
									<a href="{% url 'flags:edit_flagging_rule' flagging_rule.id %}" role="button" draggable="false" class="govuk-link govuk-link--no-visited-state">{% lcs 'FlaggingRules.List.EDIT' %}</a>
								</li>
								<li class="govuk-table__cell__actions-list-item">
									{% if flagging_rule.status == 'Active' %}
										<a href="{% url 'flags:change_flagging_rule_status' flagging_rule.id 'Deactivated' %}" role="button" draggable="false" class="govuk-link govuk-link--no-visited-state">{% lcs 'FlaggingRules.List.DEACTIVATE' %}</a>
									{% elif flagging_rule.status == 'Deactivated' %}
										<a href="{% url 'flags:change_flagging_rule_status' flagging_rule.id 'Active' %}" role="button" draggable="false" class="govuk-link govuk-link--no-visited-state">{% lcs 'FlaggingRules.List.REACTIVATE' %}</a>
									{% endif %}
								</li>
							</ul>
						{% endif %}
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% if data.total_pages > 1 %}
		<br>
		<div class="lite-pagination__container ">
			{% for i in data.total_pages|times %}
				<a href="{% url 'flags:flagging_rules' %}?{{ params_str }}&page={{ i }}" class="lite-pagination__item {% if page == i %}lite-pagination__item--selected{% endif %}" id="page-{{ i }}">
					{{ i }}
				</a>
			{% endfor %}
		</div>
	{% endif %}

{% endblock %}

templates/flags/index.html
{% extends 'layouts/base.html' %}

{% block back_link %}{% endblock %}

{% block body %}
	<div class="lite-app-bar">
		<div class="lite-app-bar__content">
			<h1 class="govuk-heading-l">
				{% block title %}
					{% lcs 'flags.FlagsList.TITLE' %}
				{% endblock %}
			</h1>
			<p class="govuk-caption-m">
				{% lcs 'flags.FlagsList.DESCRIPTION' %}
			</p>
		</div>
		<div class="lite-app-bar__controls">
			<a href="{% url 'flags:add' %}" class="govuk-button" draggable="false" role="button" id="add-a-flag-button">
				{% lcs 'flags.FlagsList.CREATE_BUTTON' %}
			</a>
		</div>
	</div>

	{% include "filters.html" %}

	{% if data.flags %}
		<table class="govuk-table">
			<thead class="govuk-table__head">
				<tr class="govuk-table__row">
					<th class="govuk-table__header" scope="col">{% lcs 'flags.FlagsList.Table.NAME' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'flags.FlagsList.Table.TEAM' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'flags.FlagsList.Table.LEVEL' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'flags.FlagsList.Table.STATUS' %}</th>
					<th class="govuk-table__header" scope="col">{% lcs 'flags.FlagsList.Table.ACTIONS' %}</th>
				</tr>
			</thead>
			<tbody class="govuk-table__body">
				{% for flag in data.flags %}
					<tr class="govuk-table__row">
						<td class="govuk-table__cell">
							<a href="{% url 'flags:flag' flag.id %}" class="govuk-link govuk-link--no-visited-state">
								{{ flag.name }}
							</a>
						</td>
						<td class="govuk-table__cell">
							{{ flag.team.name }}
						</td>
						<td class="govuk-table__cell">
							{{ flag.level }}
						</td>
						<td class="govuk-table__cell">
							{{ flag.status }}
						</td>
						<td class="govuk-table__cell govuk-table__cell--tight">
							{% if user_data.user.team.id == flag.team.id %}
								<ul class="govuk-table__cell__actions-list">
									<li class="govuk-table__cell__actions-list-item">
										{% if flag.status == 'Active' %}
											<a href="{% url 'flags:change_status' flag.id 'deactivate' %}" role="button" draggable="false" class="govuk-link govuk-link--no-visited-state">{% lcs 'flags.FlagsList.Table.DEACTIVATE' %}</a>
										{% elif flag.status == 'Deactivated' %}
											<a href="{% url 'flags:change_status' flag.id 'reactivate' %}" role="button" draggable="false" class="govuk-link govuk-link--no-visited-state">{% lcs 'flags.FlagsList.Table.REACTIVATE' %}</a>
										{% endif %}
									</li>
									<li class="govuk-table__cell__actions-list-item">
										<a href="{% url 'flags:edit' flag.id %}" class="govuk-link govuk-link--no-visited-state">{% lcs 'flags.FlagsList.Table.EDIT' %}</a>
									</li>
								</ul>
							{% else %}
								{{ None|default_na }}
							{% endif %}
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		{% include "includes/notice.html" with text='flags.FlagsList.NO_CONTENT_NOTICE' %}
	{% endif %}
{% endblock %}

templates/flags/profile.html
{% extends 'layouts/two-pane.html' %}

{% block back_link %}
	<a href="#" class="govuk-back-link">Back</a>
{% endblock %}

{% block two_thirds %}
	<h1 class="govuk-heading-xl">
		{{ title }}
	</h1>

	<dl class="govuk-summary-list">
		<div class="govuk-summary-list__row">
			<dt class="govuk-summary-list__key">
				Name
			</dt>
			<dd class="govuk-summary-list__value">
				{{ data.flag.name }}
			</dd>
		</div>
		<div class="govuk-summary-list__row">
			<dt class="govuk-summary-list__key">
				Team
			</dt>
			<dd class="govuk-summary-list__value">
				{{ data.flag.team.name }}
			</dd>
		</div>
	</dl>

	<div class="lite-user-profile-container">
		<a href="{% url 'flags:edit' data.flag.id %}" class="govuk-button govuk-button--secondary">Edit</a>
		{% if data.flag.status == 'Active' %}
			<a href="{% url 'flags:change_status' data.flag.id 'deactivate' %}" role="button" draggable="false" class="govuk-button govuk-button--warning govuk-!-margin-right-2">Deactivate</a>
		{% elif data.flag.status == 'Deactivated' %}
			<a href="{% url 'flags:change_status' data.flag.id 'reactivate' %}" role="button" draggable="false" class="govuk-button govuk-!-margin-right-2">Reactivate</a>
		{% endif %}
	</div>
{% endblock %}